// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApi.DbContexts;

#nullable disable

namespace ProductApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("ProductApi.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Category 5"
                        });
                });

            modelBuilder.Entity("ProductApi.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Thasdsadasdsadsadsa",
                            Name = "Product 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
